Added View Makers
DabYeet123/CSC207Project pull request #20
Opened 2024-11-18 20:43 UTC by DabYeet123

2024-11-18 21:38 UTC, smauloni requested changes
Launch.java should not be under a folder called Launcher
All functionalities should have a folder called with their name, under which there is 1 file for the logic (Controller) and 1 for the views (Presenter).

2024-11-20 23:05 UTC, Jackzhengqaq approved these changes

2024-11-20 23:07 UTC, Jackzhengqaq approved these changes

2024-11-20 23:07 UTC, Jackzhengqaq approved these changes

2024-11-20 23:09 UTC, closed without merging